#!/bin/bash


launch_vpn() {
	if [ ! -f "/tmp/vpn_info" ]
	then
		while :
		do
			nordvpn status > /tmp/vpn_info
			sleep 10;
		done
	fi
}

get_vpn_info() {
	good_color="#00FF00"
	bad_color="#FF0000"
	color=$good_color
	prefix='"name":"playing","instance":"ncmpcpp","color":"'
	text_tag='","full_text":"'
	sufix='"},{'
	is_connected=$(awk '
	BEGIN {
	status=""
	country=""
	city=""
} {
	if (match($0, /Status: (.*)/, groups))
		status=groups[1]
	if (match($0, /Country: (.*)/, groups))
		country=groups[1]
	if (match($0, /City: (.*)/, groups))
		city=groups[1]
}
END {
	if (status == "Connected")
		print country"/"city
	else
		print "X"
}' /tmp/vpn_info)
	if [[ $is_connected != "X" ]]
	then
		color=$good_color
	else
		color=$bad_color
	fi

	echo $prefix$color$text_tag$is_connected$sufix
}

trap "rm /tmp/vpn_info" INT

launch_vpn &

i3status -c $HOME/.config/i3/i3status_extra.conf | while :
do
	read line
	status_json=$(get_vpn_info)
	line=${line/[{/[{$status_json}
	echo "${line}" || exit 1
done

rm /tmp/vpn_info



