#!/bin/bash

get_current_res () {
	local res=$(xrandr | grep \* | awk '{print $1}')
	echo -n $res;
}

get_screen_dim () {
	local dim=$(xrandr | sed -n \
		's/.*connected\sprimary\s\([0-9x+]*\).*(.*)\s\([0-9mx\s]*\)/\2/p');
	dim=$(echo $dim | sed 's/mm\|\s//g')
}

get_hor_res () {
	local hor_res=$(get_current_res | sed -n 's/\([0-9]+\)x[0-9]+/\1/p');
	echo -n $hor_res;
}

get_current_dpi () {
	local dpi=$(xrdb -query | sed -n 's/Xft.dpi:\s*\([0-9]*\)/\1/p');
	echo -n $dpi
}

get_i3_font () {
	local i3_path=$HOME/.config/i3/config
	local size=$(sed -n 's/font\spango\:FontAwesome\s\([0-9]*\)/\1/p' $i3_path);
	# res=1366x768 and dpi=96 => font=12
	echo -n $size;
}

change_i3_font () {
	local base_str="font\spango\:FontAwesome\s";
	local font_size=$(get_hor_res);
	let "font_size=font_size/137";
	local string="s/$base_str[0-9]*/$base_str$font_size/p";
}

