#!/bin/bash

install_vundle () {
	git clone  https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
}

install_packages () {
	sudo apt install -y \
		cscope \
		lightdm-gtk-greeter-settings \
		network-manager-gnome \
		thunar \
		pavucontrol \
		tmux \
		vim \
		zathura \
		scrot
	sudo apt install xfonts-terminus fonts-font-awesome fontconfig
}

config_keyboard () {
	sudo cp etc/default/keyboard /etc/default/keyboard
}

config_lightdm () {
	sudo cp etc/lightdm/lightdm* /etc/lightdm/
}

create_symlinks () {
	mv $HOME/.bashrc{,.old}
	mv $HOME/.config/i3{,.old}
	ln -srf i3 $HOME/.config/i3
	ln -srf .bashrc $HOME/
	ln -srf .bashrc.d $HOME/
	ln -srf .tmux.conf $HOME/
	ln -srf .Xdefault $HOME/
	ln -srf .Xdefault.d $HOME/
	ln -srf .vimrc $HOME/
	ln -srf .xsessionrc $HOME/
}

install_vimpkgs () {
	vim -c PluginInstall  -c quitall
}


case $1 in
"doit")
	install_vundle
	install_packages
	config_keyboard
	config_lightdm
	create_symlinks
	install_vimpkgs
esac
