#!/bin/bash

install_vundle () {
	git clone  https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
}

install_packages () {
	sudo apt install -y \
		cscope \
		lightdm-gtk-greeter-settings \
		network-manager-gnome \
		thunar \
		pavucontrol \
		tmux \
		vim \
		zathura \
		scrot \
		lm-sensors
	sudo apt install xfonts-terminus fonts-font-awesome fontconfig
}

config_keyboard () {
	sudo cp etc/default/keyboard /etc/default/keyboard
}

config_lightdm () {
	sudo cp etc/lightdm/lightdm* /etc/lightdm/
}

create_symlinks () {
	mv $HOME/.bashrc{,.old}
	mv $HOME/.config/i3{,.old}
	mv $HOME/.config/'gtk-3.0'{,.old}
	ln -srf i3 $HOME/.config/i3
	ln -srf .bashrc $HOME/
	ln -srf .bashrc.d $HOME/
	ln -srf .tmux.conf $HOME/
	ln -srf .Xdefault $HOME/
	ln -srf .Xdefault.d $HOME/
	ln -srf .vimrc $HOME/
	ln -srf .xsessionrc $HOME/
	ln -srf {,$HOME/.config/}gtk-3.0
}

config_temperature() {
	sudo sensors-detect --auto 1>/dev/null 3>&1
}

install_vimpkgs () {
	vim -c PluginInstall  -c quitall
}

function install_urxvt() {
	xrdb -merge $HOME/.Xdefault
}

function main() {
	install_vundle
	install_packages
	config_keyboard
	config_lightdm
	create_symlinks
	install_vimpkgs
	install_urxvt
}

main
